# Federation service provided by StellarID.io
FEDERATION_SERVER="https://stellarid.io/federation/"
[[CURRENCIES]]
code = "WSD"
conditions = "WSD Tokens are issued when $ USD deposits are made and burned when $USD deposits are redeemed"
desc = "The White Standard is a stable coin 100% backed by and redeemable for $USD"
display_decimals = 2
image = "https://www.thewwallet.com/logowsd.png"
issuer = "GDSVWEA7XV6M5XNLODVTPCGMAJTNBLZBXOFNQD3BNPNYALEYBNT6CE2V"
name = "White Standard Dollar"
anchor_asset_type="fiat"
anchor_asset="USD"
is_asset_anchored = "true"
redemption_instructions = "Redeemable through https://thewwallet.com or through SEP-006 via thewwallet.com API"
[[CURRENCIES]]
code = "WSEUR"
conditions = "WSE Tokens are issued when € EURO deposits are made and burned when EURO deposits are redeemed"
desc = "The White Standard Euro is a stable coin 100% backed by and redeemable for EURO"
display_decimals = 2
image = "https://www.thewwallet.com/logowse.png"
issuer = "GDSVWEA7XV6M5XNLODVTPCGMAJTNBLZBXOFNQD3BNPNYALEYBNT6CE2V"
name = "White Standard Euro"
anchor_asset_type="fiat"
anchor_asset="EUR"
is_asset_anchored = "true"
redemption_instructions = "Redeemable through https://thewwallet.com or through SEP-006 via thewwallet.com API"
[[CURRENCIES]]
code = "WSGBP"
conditions = "WSP Tokens are issued when £ GBP deposits are made and burned when GBP deposits are redeemed"
desc = "The White Standard Pound is a stable coin 100% backed by and redeemable for GBP"
display_decimals = 2
image = "https://www.thewwallet.com/logowsp.png"
issuer = "GDSVWEA7XV6M5XNLODVTPCGMAJTNBLZBXOFNQD3BNPNYALEYBNT6CE2V"
name = "White Standard Pound"anchor_asset_type="fiat"
anchor_asset="GBP"
is_asset_anchored = "true"
redemption_instructions = "Redeemable through https://thewwallet.com or through SEP-006 via thewwallet.com API"
